name: event_orientation_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  path: ^1.9.0
  image_picker: ^1.1.2
  carousel_slider: ^4.2.1
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  equatable: ^2.0.5
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/
