import 'package:flutter/material.dart';

class TTIcons {
  TTIcons._();
  static const IconData price = Icons.price_change;
  static const IconData add_event = Icons.add_chart;
  static const IconData add_theme = Icons.add_sharp;
  static const IconData event = Icons.event;
  static const IconData description = Icons.description;
  static const IconData services = Icons.design_services;
  static const IconData search = Icons.search_outlined;
  static const IconData close = Icons.close_rounded;
  static const IconData home = Icons.home;
  static const IconData notification = Icons.notifications;
  static const IconData favourite = Icons.favorite;
  static const IconData dashboard = Icons.dashboard;
  static const IconData checkbox = Icons.check_box;
  static const IconData arrowback = Icons.arrow_back;
  static const IconData arrowright = Icons.arrow_forward;
  static const IconData arrowcircleright = Icons.arrow_circle_right_outlined;
  static const IconData arrowrightios = Icons.arrow_forward_ios;
  static const IconData arrowbackios = Icons.arrow_back_ios_new;
  static const IconData arrowdown = Icons.keyboard_arrow_down_outlined;
  static const IconData setting = Icons.settings;
  static const IconData help = Icons.help;
  static const IconData logout = Icons.logout;
  static const IconData mail = Icons.mail;
  static const IconData call = Icons.call;
  static const IconData location = Icons.location_on;
  static const IconData profileRounded = Icons.person_2_rounded;
  static const IconData emailRounded = Icons.email_rounded;
  static const IconData mobileRounded = Icons.mobile_friendly_rounded;
  static const IconData school = Icons.school_rounded;
  static const IconData address = Icons.location_city;
  static const IconData calender = Icons.calendar_today_rounded;
  static const IconData fileupload = Icons.file_upload_rounded;
  static const IconData imageupload = Icons.image;
  static const IconData work = Icons.work_history_rounded;
  static const IconData pass = Icons.password;
  static const IconData details = Icons.details;
  static const IconData feedback = Icons.feedback;
  static const IconData contactMail = Icons.contact_mail;
  static const IconData dataUsage = Icons.data_usage;
  static const IconData persons = Icons.people_rounded;
  static const IconData Themeselect = Icons.draw_rounded;
  static const IconData visibility = Icons.visibility;
  static const IconData visibility_off = Icons.visibility_off;
}
