// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAn20QZ0smGMEd6Mc3TY0upyXCJcMwdiw',
    appId: '1:246734962391:web:b1abdea8a0e9388ebdba92',
    messagingSenderId: '246734962391',
    projectId: 'event-orientation-app-7829e',
    authDomain: 'event-orientation-app-7829e.firebaseapp.com',
    storageBucket: 'event-orientation-app-7829e.appspot.com',
    measurementId: 'G-5B3FR2N4NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_PNTmXG1yFajmPijmFoD_jzZvt09s0VY',
    appId: '1:246734962391:android:ce56db7e4793a261bdba92',
    messagingSenderId: '246734962391',
    projectId: 'event-orientation-app-7829e',
    storageBucket: 'event-orientation-app-7829e.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAn20QZ0smGMEd6Mc3TY0upyXCJcMwdiw',
    appId: '1:246734962391:web:3e18781bdd0dbcdabdba92',
    messagingSenderId: '246734962391',
    projectId: 'event-orientation-app-7829e',
    authDomain: 'event-orientation-app-7829e.firebaseapp.com',
    storageBucket: 'event-orientation-app-7829e.appspot.com',
    measurementId: 'G-54ED6P87LT',
  );
}
